### PR TITLE
Calendso chart first draft

### PR DESCRIPTION
**Pull request by tinyzimmer**
Haven't put it through extensive testing yet, mainly because I've never used the product before. But seems to start okay so far 😛

### CODE REVIEW

**Comment by josephedward** [comment]
This is a really handy chart - fwiw, when I tried to use calendso the challenge was verifying the domain with google search console to be able to use any of the google reminders etc - given we have our gcp credentials in the chart, is there a way to programmatically make that request to the gcp api?

**Review by kav — APPROVED** [review]

**Comment by tinyzimmer** [comment]
> This is a really handy chart - fwiw, when I tried to use calendso the challenge was verifying the domain with google search console to be able to use any of the google reminders etc - given we have our gcp credentials in the chart, is there a way to programmatically make that request to the gcp api?

If I think I'm understanding you correctly, probably not? That's kinda one of the downsides of helm, you don't have the ability to programmatically do stuff like that, and where you do, it's not in a very idempotent way.

At my first look at this application, it almost felt to me like it warrants an operator.

**Comment by josephedward** [comment]
> > This is a really handy chart - fwiw, when I tried to use calendso the challenge was verifying the domain with google search console to be able to use any of the google reminders etc - given we have our gcp credentials in the chart, is there a way to programmatically make that request to the gcp api?
> 
> If I think I'm understanding you correctly, probably not? That's kinda one of the downsides of helm, you don't have the ability to programmatically do stuff like that, and where you do, it's not in a very idempotent way.
> 
> At my first look at this application, it almost felt to me like it warrants an operator.

I don't know as much as you do about kubernetes, but it seems like it could use an operator. Not sure if there's even a way to do that programmatically at all, being somewhat sensitive and subject to human review (of the proposed domain to search console). I guess there could be directions to get a domain approved, then deploy the chart. Or could use some other scheduling and email libraries to replicate the reminders...I guess you could put that code in an operator and wouldn't need google at all. Tedious, but then no one would know about your meetings? Is calendso's more privacy-centric hosting service open for registration?

**Comment by tinyzimmer** [comment]
I clearly need to play with it more to get more context on the flow you are describing. Part of me wanted to throw it up on a private cluster and play around with it anyway, since I've never used it or calendly before. 

Where in the helm chart you have the option to give me the name of a secret, I don't have the ability to actually fetch the contents of that secret. **But**, an operator would be a different story. It would have access to the K8s APIs and be able to programmatically interact with the secret values and such. Could even do things like generate the CalDav key in a cleaner manner than helm provides (which I opted to avoid entirely).

**Pull request closed without merging**
